CATEGORY_PRIMARY_PHRASES = {
    "personal_data": [
        "we collect",
        "we automatically collect",
        "collect information",
        "collect personal information",
        "collect personal data",
        "name",
        "email address",
        "phone number",
        "date of birth",
    ],
    "location": [
        "collect your location",
        "collect location",
        "location data",
        "location information",
        "gps",
        "geolocation",
        "precise location",
        "approximate location",
    ],
    "tracking": [
        "cookies",
        "cookie",
        "tracking technologies",
        "web beacons",
        "pixels",
        "tracking",
    ],
    "third_party_sharing": [
        "share your information",
        "share your data",
        "third parties",
        "third-party",
        "service providers",
        "business partners",
        "vendors",
        "disclose your information",
    ],
    "retention": [
        "retain your data",
        "retain your information",
        "retain your personal information",
        "data retention",
        "retention period",
        "how long we keep",
        "stored for",
        "keep your information",
        "keep your data",
        "for as long as necessary",
    ],
    "user_rights": [
        "right to access",
        "right to delete",
        "right to object",
        "access your information",
        "correct your information",
        "delete your account",
        "delete your data",
    ],
    "camera": [
        "camera",
        "camera access",
        "access your camera",
        "camera permission",
    ],
    "microphone": [
        "microphone",
        "microphone access",
        "access your microphone",
        "microphone permission",
    ],
    "security": [
        "encryption",
        "encrypted",
        "security measures",
        "security safeguards",
        "data security",
        "secure your data",
    ],
    "consent": [
        "your consent",
        "with your consent",
        "consent to",
        "you agree",
        "consent to the processing",
    ],
    "personalized_advertising": [
        "personalized advertising",
        "personalised advertising",
        "targeted advertising",
        "interest-based advertising",
        "behavioral advertising",
        "advertising partners",
    ],
    "children": [
        "children",
        "child",
        "under 13",
        "under 16",
        "minors",
        "children's data",
        "children's information",
    ],
}
